import type { Role } from "../types";

export const stubRoles: Role[] = [
  // Public Safety
  {
    id: "emergency-dispatcher",
    title: "Emergency Dispatcher",
    sectorId: "public-safety",
    openCount: 18,
    urgency: "critical",
    requiredSkills: ["crisis-management", "emergency-medical-response"],
    avgTimeToFill: 45,
  },
  {
    id: "paramedic",
    title: "Paramedic / EMT",
    sectorId: "public-safety",
    openCount: 24,
    urgency: "critical",
    requiredSkills: ["emergency-medical-response", "patient-triage", "hazmat-handling"],
    avgTimeToFill: 38,
  },
  {
    id: "site-safety-officer",
    title: "Site Safety Officer",
    sectorId: "public-safety",
    openCount: 9,
    urgency: "watch",
    requiredSkills: ["osha-regulations", "crisis-management", "hazmat-handling"],
    avgTimeToFill: 52,
  },
  // Healthcare
  {
    id: "icu-nurse",
    title: "ICU / Critical Care Nurse",
    sectorId: "healthcare",
    openCount: 41,
    urgency: "critical",
    requiredSkills: ["patient-triage", "clinical-documentation"],
    avgTimeToFill: 60,
  },
  {
    id: "health-informatics-analyst",
    title: "Health Informatics Analyst",
    sectorId: "healthcare",
    openCount: 14,
    urgency: "watch",
    requiredSkills: ["sql-data-engineering", "medical-coding", "clinical-documentation"],
    avgTimeToFill: 55,
  },
  {
    id: "medical-coder",
    title: "Medical Coder",
    sectorId: "healthcare",
    openCount: 22,
    urgency: "watch",
    requiredSkills: ["medical-coding", "clinical-documentation"],
    avgTimeToFill: 30,
  },
  // Technology
  {
    id: "cloud-architect",
    title: "Cloud Solutions Architect",
    sectorId: "technology",
    openCount: 11,
    urgency: "watch",
    requiredSkills: ["aws-architecture", "kubernetes-orchestration", "api-design"],
    avgTimeToFill: 72,
  },
  {
    id: "cybersecurity-engineer",
    title: "Cybersecurity Engineer",
    sectorId: "technology",
    openCount: 8,
    urgency: "critical",
    requiredSkills: ["devsecops", "aws-architecture", "api-design"],
    avgTimeToFill: 90,
  },
  {
    id: "devops-engineer",
    title: "DevOps Engineer",
    sectorId: "technology",
    openCount: 15,
    urgency: "stable",
    requiredSkills: ["kubernetes-orchestration", "cicd-pipelines", "devsecops"],
    avgTimeToFill: 48,
  },
  // Construction
  {
    id: "civil-engineer",
    title: "Civil Engineer",
    sectorId: "construction",
    openCount: 28,
    urgency: "watch",
    requiredSkills: ["osha-regulations", "process-improvement"],
    avgTimeToFill: 65,
  },
  // Education
  {
    id: "curriculum-designer",
    title: "Curriculum Designer",
    sectorId: "education",
    openCount: 12,
    urgency: "stable",
    requiredSkills: ["workforce-planning"],
    avgTimeToFill: 42,
  },
  // Logistics
  {
    id: "logistics-coordinator",
    title: "Logistics Coordinator",
    sectorId: "logistics",
    openCount: 67,
    urgency: "critical",
    requiredSkills: ["supply-chain-optimization", "fleet-management", "hazmat-handling"],
    avgTimeToFill: 28,
  },
  {
    id: "supply-chain-analyst",
    title: "Supply Chain Analyst",
    sectorId: "logistics",
    openCount: 19,
    urgency: "watch",
    requiredSkills: ["supply-chain-optimization", "sql-data-engineering", "process-improvement"],
    avgTimeToFill: 50,
  },
  // Finance
  {
    id: "risk-analyst",
    title: "Risk Analyst",
    sectorId: "finance",
    openCount: 7,
    urgency: "stable",
    requiredSkills: ["predictive-modeling", "sql-data-engineering", "process-improvement"],
    avgTimeToFill: 58,
  },
  // Retail
  {
    id: "retail-store-manager",
    title: "Retail Store Manager",
    sectorId: "retail",
    openCount: 35,
    urgency: "watch",
    requiredSkills: ["workforce-planning", "process-improvement"],
    avgTimeToFill: 22,
  },
];
