import type { Sector } from "../types";

export const stubSectors: Sector[] = [
  {
    id: "public-safety",
    name: "Public Safety",
    pulseScore: 34,
    status: "critical",
    description: "Police, fire, emergency medical services, and emergency management for the region.",
    employeeCount: 48200,
    openRolesCount: 312,
    kpis: [
      { label: "Postings (7d)", value: 214, delta: 12, status: "critical" },
      { label: "WoW Change", value: "+12%", delta: 12, status: "critical" },
      { label: "Critical Roles", value: 8, delta: 3, status: "critical" },
      { label: "Unmapped Skills", value: 11, delta: 2, status: "watch" },
    ],
    sparklineData: [180, 195, 214, 200, 220, 210, 214],
  },
  {
    id: "healthcare",
    name: "Healthcare",
    pulseScore: 52,
    status: "watch",
    description: "Hospitals, clinics, nursing facilities, and allied health services.",
    employeeCount: 124500,
    openRolesCount: 589,
    kpis: [
      { label: "Postings (7d)", value: 412, delta: -8, status: "watch" },
      { label: "WoW Change", value: "-8%", delta: -8, status: "watch" },
      { label: "Critical Roles", value: 5, delta: 1, status: "watch" },
      { label: "Unmapped Skills", value: 7, delta: -1, status: "stable" },
    ],
    sparklineData: [450, 430, 420, 412, 400, 408, 412],
  },
  {
    id: "technology",
    name: "Technology",
    pulseScore: 78,
    status: "stable",
    description: "Software, IT services, cybersecurity, and data infrastructure companies.",
    employeeCount: 89300,
    openRolesCount: 203,
    kpis: [
      { label: "Postings (7d)", value: 156, delta: 4, status: "stable" },
      { label: "WoW Change", value: "+4%", delta: 4, status: "stable" },
      { label: "Critical Roles", value: 2, delta: -1, status: "stable" },
      { label: "Unmapped Skills", value: 4, delta: 0, status: "stable" },
    ],
    sparklineData: [148, 152, 149, 155, 158, 154, 156],
  },
  {
    id: "construction",
    name: "Construction",
    pulseScore: 45,
    status: "watch",
    description: "Residential, commercial, and infrastructure construction and skilled trades.",
    employeeCount: 67100,
    openRolesCount: 441,
    kpis: [
      { label: "Postings (7d)", value: 298, delta: 9, status: "watch" },
      { label: "WoW Change", value: "+9%", delta: 9, status: "watch" },
      { label: "Critical Roles", value: 4, delta: 2, status: "watch" },
      { label: "Unmapped Skills", value: 8, delta: 3, status: "critical" },
    ],
    sparklineData: [260, 270, 285, 290, 295, 300, 298],
  },
  {
    id: "education",
    name: "Education",
    pulseScore: 61,
    status: "stable",
    description: "K-12 schools, community colleges, universities, and vocational training providers.",
    employeeCount: 95400,
    openRolesCount: 178,
    kpis: [
      { label: "Postings (7d)", value: 124, delta: 2, status: "stable" },
      { label: "WoW Change", value: "+2%", delta: 2, status: "stable" },
      { label: "Critical Roles", value: 2, delta: 0, status: "stable" },
      { label: "Unmapped Skills", value: 3, delta: -1, status: "stable" },
    ],
    sparklineData: [118, 120, 122, 120, 124, 123, 124],
  },
  {
    id: "logistics",
    name: "Logistics",
    pulseScore: 38,
    status: "critical",
    description: "Warehousing, freight, transportation, and last-mile delivery operations.",
    employeeCount: 73800,
    openRolesCount: 527,
    kpis: [
      { label: "Postings (7d)", value: 348, delta: 18, status: "critical" },
      { label: "WoW Change", value: "+18%", delta: 18, status: "critical" },
      { label: "Critical Roles", value: 6, delta: 4, status: "critical" },
      { label: "Unmapped Skills", value: 12, delta: 5, status: "critical" },
    ],
    sparklineData: [280, 295, 310, 320, 335, 342, 348],
  },
  {
    id: "finance",
    name: "Finance",
    pulseScore: 71,
    status: "stable",
    description: "Banking, insurance, investment management, and financial advisory services.",
    employeeCount: 55600,
    openRolesCount: 134,
    kpis: [
      { label: "Postings (7d)", value: 98, delta: 1, status: "stable" },
      { label: "WoW Change", value: "+1%", delta: 1, status: "stable" },
      { label: "Critical Roles", value: 1, delta: 0, status: "stable" },
      { label: "Unmapped Skills", value: 2, delta: -1, status: "stable" },
    ],
    sparklineData: [95, 97, 96, 98, 99, 97, 98],
  },
  {
    id: "retail",
    name: "Retail",
    pulseScore: 49,
    status: "watch",
    description: "Brick-and-mortar retail, e-commerce fulfillment, and consumer goods distribution.",
    employeeCount: 102300,
    openRolesCount: 365,
    kpis: [
      { label: "Postings (7d)", value: 245, delta: 6, status: "watch" },
      { label: "WoW Change", value: "+6%", delta: 6, status: "watch" },
      { label: "Critical Roles", value: 3, delta: 1, status: "watch" },
      { label: "Unmapped Skills", value: 5, delta: 2, status: "watch" },
    ],
    sparklineData: [225, 230, 238, 240, 242, 244, 245],
  },
];
